int tab = 1;
float color1tak = 0.5;
float color2tak = 0.5;
float color3tak = 0.5;
float color10tak = 0.0;
float color20tak = 0.0;
float color30tak = 0.0;
namespace cheats {
    bool showmenu = false;
    bool xray = false;
    bool chams = false;
    bool vclip = false;
    bool chestesp = false;
    bool tracers = false;
    bool fly = false;
    bool speed = false;
    bool tphack = false;
    bool players = false;
    bool step = false;
    bool motionX = false;
    bool motionY = false;
    bool motionZ = false;
    bool killaura = false;
    bool blink = false;
    bool rainbowesp = false;
    bool boxes;
    bool fillboxy;
    float reach = 3.0;
    float vclipsize = 3.0;
    float newX = 0.0;
    float newY = 0.0;
    float newZ = 0.0;
    float motionXf = 0;
    float motionYf = 0;
    float motionZf = 0;
    //float speedmine = 2;
    float stepsize = 0.1;
    bool listapedalow = false;
    bool cavefinder = false;
    bool clearesp = false;
    bool speedmine = false;
}
namespace binds {
    int killaurabind{ 0x0 };
    int  xraybind{ 0x0 };
    int  chams{ 0x0 };
    int  flybind{ 0x0 };
    int  vclipbind{ 0x0 };
    int  cavefinderbind{ 0x0 };
    int  clearespbind{ 0x0 };
    int  playersbind{ 0x0 };
    int blinkbind{ 0x0 };
}